stages:
  - test
# Register any environment variables you need here.
variables:
 # These are magic variables. They will be used by Postgres/Docker to do our initial database setup. The keys must be named as follows. You can change the values as you see fit.
 POSTGRES_DB: 'apidb'
 POSTGRES_USER: 'postgres'
 POSTGRES_PASSWORD: 'postgres'
 FLASK_DEBUG: 'false'
 FLASK_APP: 'app.main'
 FLASK_RUN_PORT: '3330'
 FLASK_ENV: 'development'
 

# These paths will be cached in between test runs. Very useful for reducing the build time.
cache:
 paths:
 # This took some trial and error to figure out.
  - ~/.cache/pip/

stages:
  - build
  - deploy

job packaging:
  stage: build
  script: 
  - apt-get update -qy
  - apt-get install -y python-dev python-pip
  - pip install -r requirements.txt
  - python setup.py sdist bdist_wheel

job packaging:
  stage: deploy
  script: 
  - apt-get update -qy
  - apt-get install -y python-dev python-pip
  - pip install --user --upgrade twine
  - twine upload --repository-url https://test.pypi.org/legacy/ dist/*

deploy:
  only:
    refs:
      - master

